content/privacy.md
=> feat(privacy): add text about matelso

components/c-logo.vue
=> fix(logo): adjust size on small screens

components/content/c-carousel.vue
=> fix(slider): adjust width on small screens

components/content/c-icons.vue
=> fix: remove side scrolling

assets/css/prose.css
=> fix: remove side scrolling on prose pages

components/content/c-contact.vue
=> feat(seo): implement data layer

components/c-hero.vue
Query explicitly for partials.
=> refactor: update data query

components/c-hero.vue
https://github.com/nuxt/content/issues/1154#issuecomment-1165492519
=> fix(content): remove argument passed to data query

components/c-address-block.vue, components/c-hero.vue, content/_address.json
The addresses in the footer caused a hydration mismatch.
=> fix(nuxt): fix warning

components/c-opening-hours.vue, content/_opening-hours.json
=> feat(content): make opening-hours editable

app.vue, components/c-header.vue
Different layouts have different background colors.
SH-15
=> fix(layout): adjust color of sentinel

components/c-header.vue, pages/[...slug].vue
=> refactor(layouts): adjust layouts

components/content/c-faq.vue
The module is now full width.
SH-15
=> fix(modules): fix faq width

components/content/c-contact-tiles.vue
=> fix(modules): hack for contact tiles

components/c-footer.vue, components/c-header.vue, layouts/default.vue, layouts/home.vue
=> fix(layout): restrict overall max width

components/c-card.vue, components/c-footer.vue, components/c-hero.vue, components/c-image-compare-image.vue, components/content/c-page-top.vue, components/content/c-usp.vue, components/content/c-vimeo-player.vue
Use state to store cloudinary credentials.
SH-15
=> feat(state): use state for cloudinary creds

components/c-hero.vue, content/_hero.json
=> refactor(modules): make hero image configurable

content/_hero.json
=> chore(content): rename hero image

content/_hero.json
=> fix(content): fix hero image name

components/c-hero.vue, components/content/c-page-top.vue
Now no cutoffs should happen anymore.
SH-15
=> refactor(content): adjust hero images

components/content/c-hero.vue, content/_hero.json
Added missing shadow edge.
SH-15
=> fix(modules): fix hero

components/content/c-hero.vue
=> fix(modules): fix hero image position

app.vue, app/router.options.js, components/c-header.vue, components/c-link-list.vue
=> fix(router): fix scroll behaviour

components/content/c-usp.vue
=> fix: fix warnings

components/c-link-list.vue, components/c-navigation.vue
Add a trailing slash to every link.
SH-18
=> refactor(links): add trailing slashes

composables/state.js, pages/[...slug].vue
=> feat(seo): add canonical link to every page

netlify.toml, nuxt.config.js, package-lock.json, package.json
https://github.com/nuxt/framework/issues/6204
=> fix(nuxt): workaround for netlify issue

app.vue, content/privacy.md
=> fix(seo): move script to privacy page

components/content/c-testimonial.vue, content/showcase.md
=> feat(components): add testimonial slider

package-lock.json, package.json
=> feat(node): update nuxt content

package-lock.json
=> chore(node): update modules

components/content/c-card-horizontal.vue
=> fix(component): fix card images on small screens

components/c-header.vue, components/c-navigation.vue, components/c-utilities.vue, components/content/c-page-top.vue
Switch page tops to full size background image.
SH-68
=> refactor(page-top): switch to full size bg image

components/c-header.vue, components/c-navigation.vue, components/c-utilities.vue, components/content/c-hero.vue, components/content/c-page-top.vue
Switch hero to full size background image on front-page.
SH-67
=> refactor(hero): switch to full size bg image

components/c-utilities.vue, components/content/c-carousel.vue, components/content/c-slider.vue, nuxt.config.js, package-lock.json, package.json
- feat(nuxt): update to v3 stable
- chore(node): update modules
=> feat(nuxt): update to v3 stable

nuxt.config.js
=> fix(content): change favicon path

components/content/c-contact-tiles.vue, package-lock.json
=> refactor(contact boxes): change grid

package-lock.json
=> fix(navigation): show navigation
